apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-oss
  namespace: ""
  labels:
    environment: non-prod
    team: devops
spec:
  project: default
  source:
   # path: manifests/devops/artifactory-oss/helm
    path: manifests/devops/jfrog/charts/stable/artifactory-oss
    repoURL: 'https://github.com/stefengeoffrey/argocd-applications.git'
    targetRevision: HEAD
    helm:
      valueFiles: [values.yaml]
      values: ''
  destination:
    name: in-cluster	# same as https://kubernetes.default.svc
    namespace: artifactory-oss
    server: ''
  syncPolicy:
    automated: {}
