apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-oss
  namespace: ""
  labels:
    environment: non-prod
    team: devops
spec:
  project: default
  source:
    path: manifests/devops/artifactory-oss-kustomize/overlays/IL4-with-RDS-postgres
    repoURL: 'https://github.com/stefengeoffrey/argocd-manifests.git'
    targetRevision: HEAD
  destination:
    name: in-cluster	# same as https://kubernetes.default.svc
    namespace: artifactory-oss
    server: ''
  syncPolicy:
    automated: {}
