apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cluster-autoscaler
  labels:
    team: devops
    environment: non-prod
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/devops/aws-cluster-autoscaler/overlays/non-prod
    repoURL: 'repoURL: 'https://github.com/stefengeoffrey/argocd-applications.git'
    targetRevision: HEAD
  project: devops
  syncPolicy:
    automated: {}
