apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    team: devops
    environment: non-prod
spec:
  destination:
    name: in-cluster
    namespace: 'cert-manager'
  source:
    path: manifests/devops/cert-manager/overlays/non-prod
    repoURL: 'https://github.com/stefengeoffrey/B100-devops-argocd-k8-applications.git'
    targetRevision: HEAD
  project: devops
  syncPolicy:
    automated: {}


