apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: ""
  labels:
    environment: non-prod
    team: devops
spec:
  project: devops
  source:
    path: drone
    repoURL: 'https://charts.drone.io'
    targetRevision: HEAD
    helm:
      valueFiles: [values.yaml]
      values: ''
  destination:
    name: in-cluster	# same as https://kubernetes.default.svc
    namespace: default
    server: ''
  syncPolicy:
    automated: {}
