apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-secretstore
  labels:
    team: devops
    environment: non-prod
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/devops/external-secret-secretstore/overlays/non-prod
    repoURL: 'https://github.com/stefengeoffrey/B100-devops-argocd-k8-applications.git'
    targetRevision: HEAD
  project: devops
  syncPolicy:
    automated: {}
