apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  labels:
    team: devops
    environment: non-prod
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.5.3
    chart: external-secrets
  project: devops
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
