apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  labels:
    team: devops
    environment: non-prod
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/devops/nginx-ingress/overlays/non-prod
    repoURL: 'https://github.com/stefengeoffrey/B100-devops-argocd-k8-applications.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}


