apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-aws-cluster-autoscaler
  labels:
    app.kubernetes.io/instance: autoscaler
    app.kubernetes.io/name: aws-cluster-autoscaler
    helm.sh/chart: cluster-autoscaler-8.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: autoscaler
      app.kubernetes.io/name: aws-cluster-autoscaler
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: autoscaler
        app.kubernetes.io/name: aws-cluster-autoscaler
    spec:
      containers:
        - name: aws-cluster-autoscaler
          image: k8s.gcr.io/cluster-autoscaler:v1.17.1
          command:
            - ./cluster-autoscaler
            - '--cloud-provider=aws'
            - '--Namespacepace=default'
            - '--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/non-prod'
            - '--logtostderr=true'
            - '--scale-down-delay-after-add=5m'
            - '--scale-down-enabled=true'
            - '--scale-down-unneeded-time=5m'
            - '--stderrthreshold=info'
            - '--v=4'
          ports:
            - containerPort: 8085
              protocol: TCP
          env:
            - name: AWS_REGION
              value: us-east-1
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8085
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationmessagePath: /dev/termination-log
          terminationmessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
