apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemonset.yaml
- podmonitor.yaml
- rbac.yaml
- sa.yaml

patchesJson6902:
- target: 
    version: v1
    kind: DaemonSet
    name: kube-proxy
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/ports
      value: 
      - name: metrics
        containerPort: 10249
        protocol: TCP
