apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld
  labels:
    team: devops
    environment: demo
spec:
  project: default
  source:
    path: manifests/applications/helloworld
    repoURL: 'https://github.com/stefengeoffrey/argocd-applications.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
