apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:     
- target: 
    version: v1
    kind: Deployment
    name: autoscaler-aws-cluster-autoscaler
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command
      value: 
        - ./cluster-autoscaler
        - '--cloud-provider=aws'
        - '--Namespacepace=default'
        - '--node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/non-prod'
        - '--logtostderr=true'
        - '--scale-down-delay-after-add=5m'
        - '--scale-down-enabled=true'
        - '--scale-down-unneeded-time=5m'
        - '--stderrthreshold=info'
        - '--v=4'
    - op: add
      path: /spec/template/spec/containers/0/resources/limits
      value:
        cpu: 200m	
        memory: 800Mi
