apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: amazon/aws-efs-csi-driver
    newName: 602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/aws-efs-csi-driver
    newTag: v1.3.5
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newTag: v2.2.0-eks-1-18-13
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newTag: v2.1.0-eks-1-18-13
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newTag: v2.1.1-eks-1-18-13

patchesJson6902:  
- target: 
    version: v1
    kind: ServiceAccount
    name: efs-csi-controller-sa
  patch: |-
    - op: add
      path: /metadata/annotations
      value: 
        eks.amazonaws.com/role-arn: 'arn:aws:iam::prod:role/AmazonEKS_EFS_CSI_DriverRole'
