---
# Source: artifactory-oss/charts/artifactory/templates/artifactory-installer-info.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: artifactory-oss-installer-info
  labels:
    app: artifactory
    chart: artifactory-107.55.13
    heritage: Helm
    release: artifactory-oss
data:
  installer-info.json: |
    {"productId": "Helm_artifactory-oss/107.55.13", "features": [ { "featureId": "Platform/art-oss-helm"}]}
