apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-aws-cluster-autoscaler
  labels:
    app.kubernetes.io/instance: autoscaler
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: aws-cluster-autoscaler
    helm.sh/chart: cluster-autoscaler-8.0.0
rules:
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
      - endpoints
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/eviction
  - verbs:
      - update
    apiGroups:
      - ''
    resources:
      - pods/status
  - verbs:
      - get
      - update
    apiGroups:
      - ''
    resources:
      - endpoints
    resourceNamespace:
      - cluster-autoscaler
  - verbs:
      - watch
      - list
      - get
      - update
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - persistentvolumes
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
  - verbs:
      - get
      - list
      - patch
      - watch
    apiGroups:
      - batch
      - extensions
    resources:
      - jobs
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - extensions
    resources:
      - replicasets
      - daemonsets
  - verbs:
      - watch
      - list
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - apps
    resources:
      - daemonsets
      - replicasets
      - statefulsets
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - csinodes
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - create
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - get
      - update
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNamespace:
      - cluster-autoscaler
