apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  labels:
    environment: demo
spec:
  project: default
  source:
    path: charts/helm-demo
    repoURL: 'https://github.com/stefengeoffrey/demo-application.git'
    targetRevision: HEAD
    helm:
      valueFiles: [values.yaml]
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
