apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-infracost
spec:
  data:
    - secretKey: INFRACOST_API_KEY
      remoteRef:
        key: tools/devops/atlantis/infracost-credentials
        property: INFRACOST_API_KEY 
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: tools/devops/atlantis/infracost-credentials
        property: GITHUB_TOKEN  
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    creationPolicy: Owner
    name: atlantis-infracost
