apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-tf-cloud
spec:
  data:
    - secretKey: TG_TF_REGISTRY_TOKEN
      remoteRef:
        key: tools/devops/atlantis/tf-cloud-credentials
        property: TG_TF_REGISTRY_TOKEN
    # Use same value to download nested modules via terraform
    - secretKey: TF_TOKEN_app_terraform_io
      remoteRef:
        key: tools/devops/atlantis/tf-cloud-credentials
        property: TG_TF_REGISTRY_TOKEN  
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    creationPolicy: Owner
    name: atlantis-tf-cloud