apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-vault
spec:
  data:
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: tools/devops/atlantis/vault-credentials
        property: VAULT_TOKEN
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    creationPolicy: Owner
    name: atlantis-vault