apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdn-server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if or .Values.joinKey .Values.global.joinKey }}
  {{- if not (or .Values.joinKeySecretName .Values.global.joinKeySecretName) }}
  join-key: {{ include "pdn-server.joinKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if or .Values.masterKey .Values.global.masteKey }}
  {{- if not (or .Values.masterKeySecretName .Values.global.masterKeySecretName) }}
  master-key: {{ include "pdn-server.masterKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.pdnJoinKey }}
  {{- if not .Values.pdnJoinKeySecretName }}
  pdn-join-key: {{ .Values.pdnJoinKey | b64enc | quote }}
  {{- end }}
  {{- end }}

{{- $extraSecretsPrependReleaseName := .Values.extraSecretsPrependReleaseName }}
{{- range $key, $value := .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- if $extraSecretsPrependReleaseName }}
  name: {{ $.Release.Name }}-{{ $key }}
  {{- else }}
  name: {{ $key }}
  {{- end }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData: {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 2 }}
{{- end }}
