---
# Source: artifactory-oss/charts/artifactory/templates/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-oss-artifactory-nginx
  labels:
    app: artifactory
    chart: artifactory-107.55.13
    heritage: Helm
    release: artifactory-oss
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
      release: artifactory-oss
      component: nginx
  template:
    metadata:
      annotations:
        checksum/nginx-conf: e988ffe11c954ecc600311dbe1236d0ff5306e79a04e9b5d7c6870d6ede9b5b8
        checksum/nginx-artifactory-conf: ab45c4e001d76708707102a30aed0eb55ccb75dff2ff20c9c718e7086cbc4ecf
      labels:
        app: artifactory
        chart: artifactory-107.55.13
        component: nginx
        heritage: Helm
        release: artifactory-oss
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: "setup"
        image: "releases-docker.jfrog.io/ubi9/ubi-minimal:9.1.0.1760"
        imagePullPolicy: IfNotPresent
        command:
        - '/bin/sh'
        - '-c'
        - >
          rm -rfv /var/opt/jfrog/nginx/lost+found;
          mkdir -p /var/opt/jfrog/nginx/logs;
        volumeMounts:
        - mountPath: "/var/opt/jfrog/nginx"
          name: nginx-volume
      securityContext:
        runAsUser: 104
        fsGroup: 107
      containers:
      - name: nginx
        image: releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:7.55.13
        imagePullPolicy: IfNotPresent
        command:          
          - nginx
          - -g
          - 'daemon off;'
        ports:

        # DEPRECATION NOTE: The following is to maintain support for values pre 1.3.1 and
        # will be cleaned up in a later version
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-artifactory-conf
          mountPath: "/var/opt/jfrog/nginx/conf.d/"
        - name: nginx-volume
          mountPath: "/var/opt/jfrog/nginx"  
        - name: ssl-certificates
          mountPath: "/var/opt/jfrog/nginx/ssl"  
        resources:
          {}
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - curl -s -k --fail --max-time 5 http://localhost:80/router/api/v1/system/readiness
          initialDelaySeconds: 30
          failureThreshold: 90
          periodSeconds: 5
          timeoutSeconds: 5
          
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - curl -s -k --fail --max-time 5 http://localhost:80/router/api/v1/system/readiness
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
          
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - curl -s -k --fail --max-time 5 http://localhost:80/
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
          
      volumes:
      - name: nginx-conf
        configMap:
          name: artifactory-oss-nginx-conf
      - name: nginx-artifactory-conf
        configMap:
          name: artifactory-oss-nginx-artifactory-conf
      - name: nginx-volume
        emptyDir: {}
      - name: ssl-certificates
        secret:
          secretName: artifactory-oss-nginx-certificate
