apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-aws-cluster-autoscaler
  labels:
    app.kubernetes.io/instance: autoscaler
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: aws-cluster-autoscaler
    helm.sh/chart: cluster-autoscaler-8.0.0
subjects:
  - kind: ServiceAccount
    name: default
    Namespacepace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoscaler-aws-cluster-autoscaler
