---
# Source: artifactory-oss/charts/artifactory/charts/postgresql/templates/extended-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-oss-postgresql-extended-configuration
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.3.18
    app.kubernetes.io/instance: artifactory-oss
    app.kubernetes.io/managed-by: Helm
  namespace: artifactory-oss
data:

  override.conf: |
    listen_addresses = '*'
    max_connections = '1500'
