---
# Source: artifactory-oss/charts/artifactory/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-oss-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.3.18
    app.kubernetes.io/instance: artifactory-oss
    app.kubernetes.io/managed-by: Helm
  namespace: artifactory-oss
type: Opaque
data:
  postgresql-postgres-password: "NzYwMlgzNEh6Ug=="
  postgresql-password: "ZzR5V2F4M3RUaA=="
