apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-atlast
spec:
  data:
    - secretKey: MONGODB_ATLAS_PUBLIC_KEY
      remoteRef:
        key: tools/devops/atlantis/atlas-credentials
        property: MONGODB_ATLAS_PUBLIC_KEY 
    - secretKey: MONGODB_ATLAS_PRIVATE_KEY
      remoteRef:
        key: tools/devops/atlantis/atlas-credentials
        property: MONGODB_ATLAS_PRIVATE_KEY
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    creationPolicy: Owner
    name: atlantis-atlast
