apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-aws
spec:
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: tools/devops/atlantis/aws-credentials
        property: AWS_ACCESS_KEY_ID 
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: tools/devops/atlantis/aws-credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: tools/devops/atlantis/aws-credentials
        property: AWS_DEFAULT_REGION 
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    creationPolicy: Owner
    name: atlantis-aws