apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-github
spec:
  data:
    - secretKey: ATLANTIS_GH_APP_KEY
      remoteRef:
        key: tools/devops/atlantis/github-credentials
        property: ATLANTIS_GH_APP_KEY 
    - secretKey: ATLANTIS_GH_APP_ID
      remoteRef:
        key: tools/devops/atlantis/github-credentials
        property: ATLANTIS_GH_APP_ID
    - secretKey: ATLANTIS_GH_WEBHOOK_SECRET
      remoteRef:
        key: tools/devops/atlantis/github-credentials
        property: ATLANTIS_GH_WEBHOOK_SECRET 
    - secretKey: GITHUB_TOKEN # Used for GitHub Provider
      remoteRef:
        key: tools/devops/atlantis/github-credentials 
        property: GITHUB_TOKEN
  refreshInterval: 5m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-backend
  target:
    creationPolicy: Owner
    name: atlantis-github