---
# Source: artifactory-oss/charts/artifactory/templates/artifactory-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-oss
  labels:
    app: artifactory
    chart: artifactory-107.55.13
    heritage: Helm
    release: artifactory-oss
type: Opaque
data:
