---
# Source: artifactory-oss/charts/artifactory/templates/artifactory-access-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-oss-access-config
  labels:
    app: artifactory
    chart: artifactory-107.55.13
    heritage: Helm
    release: artifactory-oss
type: Opaque
stringData:
  access.config.patch.yml: |
    security:
      tls: false
