---
# Source: artifactory-oss/charts/artifactory/templates/artifactory-binarystore-secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: artifactory-oss-binarystore
  labels:
    app: artifactory
    chart: artifactory-107.55.13
    heritage: Helm
    release: artifactory-oss
stringData:
  binarystore.xml: |-
    <!-- File system filestore -->
    <config version="v1">
        <chain> <!--template="file-system"-->
                <provider id="file-system" type="file-system"/>
        </chain>
    </config>
