apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesJson6902:
# Override ConfigMap to an old one during migration to ArgoCD.
- target: 
    version: v1
    kind: ConfigMap
    name: coredns
  patch: |-
    - op: add
      path: /data/Corefile
      value: |
        .:53 {
            errors
            health
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
            }
            log . {
                class error
            }
            prometheus :9153
            forward . /etc/resolv.conf
            cache 30
            loop
            reload
            loadbalance
        }

- target:
    version: v1
    kind: Deployment
    name: coredns
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        limits:
          cpu: 50m
          memory: 50Mi
